# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyHealthApp' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

target 'HealthApp Extension' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end